Revert "Add synthetic datasets (#5315)"
This reverts commit 10088f10c6dd2ac93d4fd736a205c2954cbec27c.

Reason for rollback: Broke builds due to errors such as:

File
"/workspace/pip_test/venv/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/__init__.py",
line 29, in <module>
    from tensorflow.contrib.learn.python.learn.datasets import synthetic
    ImportError: cannot import name synthetic